---
version: "3"
services:
  assembly:
    build: ./assembly
    volumes:
      - type: volume
        source: war
        target: /tmp/war
    depends_on:
      - web
  web:
    build: ./web
    volumes:
      - type: volume
        source: war
        target: /usr/local/tomcat/webapps
    ports:
      - "7070:8080"
volumes:
  war:
